### ISSUE TITLE
is it possible to expose boost::ptr_multimap<> through this?

### ISSUE THREAD

**Issue by finjulhich** [JohnReid/boost-indexing-suite#1]

**Comment by JohnReid** [comment]
No I don't think so. It probably wouldn't be too difficult to add to the library if you wanted to have a go.

**Comment by JohnReid** [comment]
I'm not sure about that. There are quite a few versions of this code around. I needed access via a git repository so I took Roman Yakovenko's code and placed it here. It has been some time since I've looked at it. Sorry I can't be of more help.

**Comment by finjulhich** [comment]
N/A
